theme: jekyll-theme-cayman
title: "Bailey M. Barenick"
description: "MSc Candidate in Biotechnology at Pennsylvania State University in the Chopra Maize Genetics Lab"
[link text](https://media.licdn.com/dms/image/v2/D4E0BAQEYbFbIAJCUAQ/company-logo_200_200/company-logo_200_200/0/1716298147179/chopra_maize_genetics_lab_logo?e=1772668800&v=beta&t=Y1OHlVMlk4iVrLF7dCYPGM-z8qT_55Z3jGVWQyOZoFM):
![alt text](image.png)
