theme: jekyll-theme-tactile
title: "Bailey M. Barenick"
description: "MSc Candidate in Biotechnology at Pennsylvania State University in the Chopra Maize Genetics Lab"
[link text](https://extension.psu.edu/media/wysiwyg//extensions/catalog_product/607a4f36fc014ec988e18d20bba80fa4/f/a/fall-armyworm-1.jpg)
![alt text](Fall Armyworm Caterpillar)
