theme: jekyll-theme-tactile
title: "Bailey M. Barenick"
description: "MSc Candidate in Biotechnology at Pennsylvania State University in the Chopra Maize Genetics Lab"
chopra_maize_genetics_alab _logo_.jpg: /assets/images/chopra_maize_genetics_alab_logo.jpg
